### PR TITLE
chore(project): support Gatsby v4, Webpack v5

### LINKED ISSUE #15: Gatsby v4, Webpack v5
Any plans to support Gatsby v4 and Webpack v5?

Looks like the Gatsby v4 migration would just be an update to peer deps, like v3 was in #9.

Using webpack v5 in a gatsby project causes issues currently. Forcing resolution to Webpack v5 via yarn `resolutions` works in my project. Maybe the webpack dep range can be updated to webpack v4 || v5?

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #15 

This will need a publish to npm so consumers can take advantage of the updates.

### CODE REVIEW

**Comment by kakadiadarpan** [comment]
Thanks for creating the issue and PR @tay1orjones! 🙌 

I think we can just drop the support for older version now. What do you think?

**Comment by tay1orjones** [comment]
@kakadiadarpan yeah, sounds good to me. I just updated the PR

**Comment by tay1orjones** [comment]
@kakadiadarpan this should be ready to merge

**Review by kakadiadarpan — APPROVED** [review]

**Comment by kakadiadarpan** [comment]
@tay1orjones Sorry for the delay. Just merged and released a new version :)

**Pull request merged**
